version: '3.4'
services:
  db:
    image: "mcr.microsoft.com/mssql/server"
    environment:
      SA_PASSWORD: "Admin1234"
      ACCEPT_EULA: "Y"
    ports:
      - 1433:1433
  api:
    image: api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:80"